using static LeadSoft.Common.Library.Enumerators.Enums;

namespace LeadSoft.Common.GlobalDomain.Entities.CloudFiles;

/// <summary>
/// Generic entity that represents a Cloud File
/// </summary>
/// <remarks>
/// Use this class to store, delete and read any file in S3 bucket.
/// You can also create temporary links.
/// </remarks>
public partial class CloudFile : BaseEntity
{
    /// <summary>
    /// Bucket Name
    /// </summary>
    public string Bucket { get; set; } = string.Empty;

    /// <summary>
    /// File unique key generated by S3 upload
    /// </summary>
    public string Key { get; set; } = string.Empty;

    /// <summary>
    /// Title for image
    /// Use file name if title is not applicable
    /// </summary>
    public virtual string Title { get; set; }

    /// <summary>
    /// Description for image
    /// Subtitle? Maybe it's a good place to store it
    /// </summary>
    public virtual string Description { get; set; }

    /// <summary>
    /// File size in bytes
    /// </summary>
    public long Size { get; set; } = long.MinValue;

    /// <summary>
    /// File mime type
    /// </summary>
    public string FileType { get => FileExtension.GetDescription(); }

    /// <summary>
    /// File mime type
    /// </summary>
    public FileExtension FileExtension { get; set; } = FileExtension.None;

    /// <summary>
    /// Image Uri
    /// </summary>
    public virtual Uri? Url { get; set; }
}
